### ISSUE TITLE
ტექნიკურ პრობლემებზე კონსულტაცია

### ISSUE THREAD

**Issue by iarigby** [freeuni-digital-technologies/freeuni-digital-technologies.github.io#2]
პრობლემები ლექცია-სემინარიდან

- გარემოს გამართვა
  - installing java (duh)
  - running karel
  - note: unzip-ის ინსტრუქცია არის ჩასამატებელი.. extract-ს რომ უნდა დააჭირონ
- რამდენიმე კომენტარებს ვერ წერდა 
- semicolon-ებს უწერს რაღაც უცნაური ნიშნით, გუგას მივწერე ამაზე და ვნახავ რას მიპასუხებს (მიპასუხა და არ ყოფილა ასეთი შემთხვევა... არადა ახლა ორს აქვს)

**Comment by iarigby** [comment]
@khokho შეძლებ ხვალ ან ზეგ 1 საათი გამოყო კონსულტაციისთვის და დაეხმარო ამეებში?

**Comment by khokho** [comment]
ხვალ დილით 10 საათზე აწყობთ?

**Comment by iarigby** [comment]
ცხრილი ვნახე და თავისუფალია, დავპოსტავ.

**Comment by khokho** [comment]
ახალ კლასრუმშიც ჩამაგდე ბარემ.

**Comment by iarigby** [comment]
კი ვაპირებდი ნახევარ საათში ვიზამ ორივეს.

**Comment by iarigby** [comment]
@khokho მადლობა ასე მალე რომ ჩაატარე. რამე კონკრეტული პრობლემები გამოიკვეთა რისიც ინსტრუქციაში ჩამატება შეიძლება?

**Comment by khokho** [comment]
დაყენების მხრივ პრობლემა ერთი-ორს ქონდა მარტო(ერთს ვინდუსი ქონდა არეული და გადასაყენებული, მეორე მაკზე იყო პატარა პრობლემა). 
extract-ს რომ უნდა დააჭირონ მაგას ჩავამატებ მაგრამ რეალურად ფაილების შენახვა/გახსნაზე უფრო ქონდათ კითხვები.
