### ISSUE TITLE
კარელის დავალებების პირობები

### ISSUE THREAD

**Issue by iarigby** [freeuni-digital-technologies/freeuni-digital-technologies.github.io#3]
- სხვა დავალების პირობების გადატანა [პირველის ფორმატით](https://freeuni-digital-technologies.github.io/content/homework/1_karel_intro.html). 
- დავალებებისთვის world ფაილების გამზადება.

- [დავალების word ფაილები](https://drive.google.com/drive/u/2/folders/1HhVV0h0s8-Cgzy6gXGl4gdtOXCycQRQ6)

- [x] 1
- [x] 2 (ორი ცალი ამოცანაა, ცალ-ცალკე დავალებად დაემატება. (2. copyBeepers, 2. fillLine)
- [ ] 3
- [ ] 4

ამ კვირაში მარტო მეორეა აუცილებელი (milestone მაგას ეხება მარტო)

**Comment by khokho** [comment]
მეორე დავალება დავამატე.

**Comment by iarigby** [comment]
@khokho მესამე და მეოთხე დავალებებს რომ დაამატებ კლასრუმზეც გააკეთე schedule 
- გამოქვეყნდეს ორშაბათ დილას
- დავალების აღწერაში ლინკი
- დედლაინი სამშაბათი 11:59
