### ISSUE TITLE
მეოთხე დავალება

### ISSUE THREAD

**Issue by iarigby** [freeuni-digital-technologies/freeuni-digital-technologies.github.io#4]
https://codehs.com/lms/assignment/41699536

**Comment by khokho** [comment]
ის შემთხვევა მქონდეს ხაზზე პირველი კედელი რო იყოს ამოკლებული?

**Comment by iarigby** [comment]
არა

**Comment by khokho** [comment]
დანზოუ.

ბოლო კედლის შემთხვევა ჩავსვი.
